const empleadosData = 
  [
  {
    "nombre_dashboard": "Amin, Josefina",
    "area": "Administración",
    "lider_email": "marcelo@picallex.com",
    "archivo_en_drive": "AMIN, Josefina",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https:
    "fecha_trimestral": "21/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Josefina mostró gran crecimiento y ownership al resolver el balance anual, aprendiendo en tiempo real y entendiendo el impacto de su rol. Está motivada por la contabilidad argentina y busca automatizar procesos, pero necesita alinear expectativas y comunicación con su líder. También plantea la necesidad de revisar su compensación a futuro.",
    "resumen_ia": "Josefina mostró gran crecimiento y ownership al resolver el balance anual, aprendiendo en tiempo real y entendiendo el impacto de su rol. Está motivada por la contabilidad argentina y busca automatizar procesos, pero necesita alinear expectativas y comunicación con su líder. También plantea la necesidad de revisar su compensación a futuro.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "desconexión o conflicto explícito",
    "relacion_lider": "desconexión o conflicto explícito",
    "rel_con_lider": "desconexión o conflicto explícito",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "Sí",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Robledo, Lucía",
    "area": "Administración",
    "lider_email": "marcelo@picallex.com",
    "archivo_en_drive": "ROBLEDO, Lucía",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1pRfpB-e8d1KAMeD2-lwBjqf9_vv6EFMvU4iMJT2Vl2I/edit?usp=drivesdk",
    "fecha_trimestral": "21/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Lucía ha tenido un período de intenso aprendizaje y se siente desafiada por su trabajo, mostrando iniciativa en IA y automatización. Sin embargo, expresa preocupación por la microgestión de su líder, Chelo, lo que le genera dudas sobre la confianza y afecta su motivación. A pesar de esto, se ve en la empresa a fin de año y busca activamente nuevas oportunidades de crecimiento.",
    "resumen_ia": "Lucía ha tenido un período de intenso aprendizaje y se siente desafiada por su trabajo, mostrando iniciativa en IA y automatización. Sin embargo, expresa preocupación por la microgestión de su líder, Chelo, lo que le genera dudas sobre la confianza y afecta su motivación. A pesar de esto, se ve en la empresa a fin de año y busca activamente nuevas oportunidades de crecimiento.",
    "riesgo_de_fuga": "Medio",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "desconexión o conflicto explícito",
    "relacion_lider": "desconexión o conflicto explícito",
    "rel_con_lider": "desconexión o conflicto explícito",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Gonzalez, Lucía",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "GONZALEZ, Lucia",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1rpobxwK4uFigGUyOhiYBasDW3sMIvVmAtYjHhPWUYo8/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Lucía está comprometida con la IA y el trabajo en equipo, valorando la mejora de las herramientas y el apoyo de sus compañeros. Su principal frustración es la lentitud en el desarrollo técnico (AppScript) y la falta de logros concretos para mostrar. Busca mejorar su organización y autonomía técnica, viéndose en la empresa a fin de año si logra avanzar en estas áreas.",
    "resumen_ia": "Lucía está comprometida con la IA y el trabajo en equipo, valorando la mejora de las herramientas y el apoyo de sus compañeros. Su principal frustración es la lentitud en el desarrollo técnico (AppScript) y la falta de logros concretos para mostrar. Busca mejorar su organización y autonomía técnica, viéndose en la empresa a fin de año si logra avanzar en estas áreas.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Formia, Mateo",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "FORMIA, Mateo",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1VzVQuZloSy6A8eMHbc1Zy9EgYQLBkrgaNilAmHEVme0/edit?usp=drivesdk",
    "fecha_trimestral": "20/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Mateo está muy motivado y orgulloso de la evolución de su rol gracias a la IA, que le permite ser más eficiente y creativo. Tiene metas claras de escalar clientes y profesionalizar la gestión de cuentas, sintiéndose desafiado. Aunque existen roces inter-áreas y dependencias de conocimiento, se están abordando proactivamente.",
    "resumen_ia": "Mateo está muy motivado y orgulloso de la evolución de su rol gracias a la IA, que le permite ser más eficiente y creativo. Tiene metas claras de escalar clientes y profesionalizar la gestión de cuentas, sintiéndose desafiado. Aunque existen roces inter-áreas y dependencias de conocimiento, se están abordando proactivamente.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "equilibrio",
    "carga_de_trabajo": "equilibrio",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Herrera, Mauro",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Muñiz, Franco",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "Muñiz, Franco",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/11N5S7SjtbzRxuB-CMY_ywQhogzWNfUJrFColryQMbrM/edit?usp=drivesdk",
    "fecha_trimestral": "22/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Franco está muy motivado por la evolución de su rol hacia la IA y automatización, liderando proyectos clave que optimizan procesos y reducen tiempos. Muestra un fuerte compromiso con la empresa y su crecimiento, con una relación fluida con su líder y una visión clara para el futuro. Identifica áreas de mejora en la documentación y roces inter-áreas, proponiendo soluciones activamente.",
    "resumen_ia": "Franco está muy motivado por la evolución de su rol hacia la IA y automatización, liderando proyectos clave que optimizan procesos y reducen tiempos. Muestra un fuerte compromiso con la empresa y su crecimiento, con una relación fluida con su líder y una visión clara para el futuro. Identifica áreas de mejora en la documentación y roces inter-áreas, proponiendo soluciones activamente.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "equilibrio",
    "carga_de_trabajo": "equilibrio",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Navazzotti, Agus.",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "NAVAZZOTTI, Agustina",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1tvmTtWhH3Q3A0xQxPJjhkUBEUbktur7P1rLTjn8rjEE/edit?usp=drivesdk",
    "fecha_trimestral": "11/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "18/5/2026",
    "resumen": "Agus está muy motivado con la implementación de IA y nuevos proyectos, buscando eficiencias en monitoreo y guardias. Sin embargo, enfrenta una carga de trabajo excesiva debido a tareas manuales repetitivas y una sobrecarga de información sobre IA que le genera ansiedad y saturación. Mantiene buenas relaciones con su equipo y líder, aunque con roces menores y una solicitud de ajuste en la comunicación.",
    "resumen_ia": "Agus está muy motivado con la implementación de IA y nuevos proyectos, buscando eficiencias en monitoreo y guardias. Sin embargo, enfrenta una carga de trabajo excesiva debido a tareas manuales repetitivas y una sobrecarga de información sobre IA que le genera ansiedad y saturación. Mantiene buenas relaciones con su equipo y líder, aunque con roces menores y una solicitud de ajuste en la comunicación.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "agotamiento explícito",
    "carga_de_trabajo": "agotamiento explícito",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Palazesi, Nicolás",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Pérez, Victoria",
    "area": "C2R",
    "lider_email": "natalia@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Cachambú, Anto.",
    "area": "CX",
    "lider_email": "melisa@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Delfino, Milagros",
    "area": "CX",
    "lider_email": "melisa@picallex.com",
    "archivo_en_drive": "Delfino, Milagros",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/18jFTRndbBwaUTxTG87IrbJcr1sEPazb8a4xwjVpAzz0/edit?usp=drivesdk",
    "fecha_trimestral": "20/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Milagros destaca su rol en automatizaciones N8N y un cambio estratégico que liberó tareas. Muestra gran interés en QA/testing y busca capacitación técnica. Expresa agotamiento extremo por la carga de trabajo reciente, aunque valora la autonomía y la relación fluida con su líder. Su permanencia está condicionada a un desarrollo en QA/automatizaciones y un descanso real.",
    "resumen_ia": "Milagros destaca su rol en automatizaciones N8N y un cambio estratégico que liberó tareas. Muestra gran interés en QA/testing y busca capacitación técnica. Expresa agotamiento extremo por la carga de trabajo reciente, aunque valora la autonomía y la relación fluida con su líder. Su permanencia está condicionada a un desarrollo en QA/automatizaciones y un descanso real.",
    "riesgo_de_fuga": "Medio",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "agotamiento explícito",
    "carga_de_trabajo": "agotamiento explícito",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Gregoris, Fernando",
    "area": "CX",
    "lider_email": "melisa@picallex.com",
    "archivo_en_drive": "GREGORIS, Fernando",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1Kq06qAJbsZyDE6JI_lTv_XeEiEPZjTrULqBgPPI6AsE/edit?usp=drivesdk",
    "fecha_trimestral": "15/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Fernando está motivado por proyectos de IA como Tobi y el sistema de alertas con Anto, que mejorarán la capacidad de CX. Busca claridad sobre su condición comercial (sin actualizar hace 2 años) y una capacitación formal. Valora la libertad de organización y tiene buena relación con su líder, aunque pide reuniones más pausadas.",
    "resumen_ia": "Fernando está motivado por proyectos de IA como Tobi y el sistema de alertas con Anto, que mejorarán la capacidad de CX. Busca claridad sobre su condición comercial (sin actualizar hace 2 años) y una capacitación formal. Valora la libertad de organización y tiene buena relación con su líder, aunque pide reuniones más pausadas.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "equilibrio",
    "carga_de_trabajo": "equilibrio",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "Sí",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Jorge, Delfina",
    "area": "CX",
    "lider_email": "melisa@picallex.com",
    "archivo_en_drive": "JORGE, Delfina",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1ihJZ_JEef-3riXnCyEAKwCPuphqHXfjEqTQQ_P7fetQ/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Delfina es una colaboradora altamente motivada y proactiva, enfocada en la automatización con IA para optimizar procesos y reducir dependencias. Lidera múltiples iniciativas para mejorar la eficiencia del equipo y la gestión de cuentas, aunque esto implica una carga de trabajo considerable. Busca reconocimiento por sus proyectos en desarrollo y valora la autonomía.",
    "resumen_ia": "Delfina es una colaboradora altamente motivada y proactiva, enfocada en la automatización con IA para optimizar procesos y reducir dependencias. Lidera múltiples iniciativas para mejorar la eficiencia del equipo y la gestión de cuentas, aunque esto implica una carga de trabajo considerable. Busca reconocimiento por sus proyectos en desarrollo y valora la autonomía.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "pide más feedback",
    "relacion_lider": "pide más feedback",
    "rel_con_lider": "pide más feedback",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Kohler, Augusto",
    "area": "CX",
    "lider_email": "melisa@picallex.com",
    "archivo_en_drive": "KOHLER, Augusto",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1lHvIFoE5ap5C607kSBxDVbAXsXxSjkv4Nmi4XnSshoA/edit?usp=drivesdk",
    "fecha_trimestral": "19/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Augusto se enfoca en automatizar tareas y optimizar procesos con IA, mostrando iniciativa para mejorar la colaboración y reducir la carga de trabajo. Valora la autonomía y el espacio con su líder, sintiéndose motivado y con mayor confianza. Proyecta su futuro en la empresa y busca formación en IA.",
    "resumen_ia": "Augusto se enfoca en automatizar tareas y optimizar procesos con IA, mostrando iniciativa para mejorar la colaboración y reducir la carga de trabajo. Valora la autonomía y el espacio con su líder, sintiéndose motivado y con mayor confianza. Proyecta su futuro en la empresa y busca formación en IA.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Lourenco, Candela",
    "area": "CX",
    "lider_email": "melisa@picallex.com",
    "archivo_en_drive": "Lourenco, Candela",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1R8Gg4aWFzyhcD8DN4Hbvk_poOx2sJOUFyGqYStu5mE8/edit?usp=drivesdk",
    "fecha_trimestral": "20/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Candela demuestra proactividad en la implementación de IA para optimizar procesos, destacando su bot Pivot y planes de automatización. Sin embargo, expresa un claro deseo de transición de su rol de soporte hacia UX/diseño, buscando activamente oportunidades externas. A pesar del agotamiento por el soporte, valora el buen clima y alineación del equipo.",
    "resumen_ia": "Candela demuestra proactividad en la implementación de IA para optimizar procesos, destacando su bot Pivot y planes de automatización. Sin embargo, expresa un claro deseo de transición de su rol de soporte hacia UX/diseño, buscando activamente oportunidades externas. A pesar del agotamiento por el soporte, valora el buen clima y alineación del equipo.",
    "riesgo_de_fuga": "Alto",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "agotamiento explícito",
    "carga_de_trabajo": "agotamiento explícito",
    "motivacion": "desencanto o falta de norte",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Alvarez, Germán",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "ALVAREZ, Germán",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1JsbcShzZc4K6h2jk0hV3dHSJfkTM3P3GHtA7RoHCYcw/edit?usp=drivesdk",
    "fecha_trimestral": "19/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Germán muestra un gran crecimiento personal y profesional, asumiendo nuevos roles técnico-comerciales y liderando iniciativas con IA. Está altamente motivado por nuevos desafíos y el reconocimiento, con una relación fluida con su líder. Sin embargo, expresa preocupación por ser un punto único de fallo en integraciones críticas y la ansiedad por la velocidad del cambio tecnológico, además de identificar roces en el equipo que requieren intervención.",
    "resumen_ia": "Germán muestra un gran crecimiento personal y profesional, asumiendo nuevos roles técnico-comerciales y liderando iniciativas con IA. Está altamente motivado por nuevos desafíos y el reconocimiento, con una relación fluida con su líder. Sin embargo, expresa preocupación por ser un punto único de fallo en integraciones críticas y la ansiedad por la velocidad del cambio tecnológico, además de identificar roces en el equipo que requieren intervención.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Alvarez, Cristian",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "Alvarez, Cristian",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1zDsAE1fPxj9Y5orfdM6piP5o7-V8vq3FRgJrXgDBRtU/edit?usp=drivesdk",
    "fecha_trimestral": "22/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Cristian es un colaborador clave en proyectos complejos de IA y permisos de plataformas, destacando su habilidad para navegar la burocracia. Identifica una dependencia crítica en su rol y propone delegar tareas operativas para mitigar el esfuerzo excesivo. Muestra compromiso con su camino profesional y buena relación con su equipo y líderes, adaptándose a su nueva paternidad.",
    "resumen_ia": "Cristian es un colaborador clave en proyectos complejos de IA y permisos de plataformas, destacando su habilidad para navegar la burocracia. Identifica una dependencia crítica en su rol y propone delegar tareas operativas para mitigar el esfuerzo excesivo. Muestra compromiso con su camino profesional y buena relación con su equipo y líderes, adaptándose a su nueva paternidad.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Calcagno, Camila",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Franco, Federico",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "FRANCO, Federico",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/11iSXol963tW-oxnGO2OVoAeI_WwV-hk9BgxYgVI-Ioc/edit?usp=drivesdk",
    "fecha_trimestral": "18/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Federico es un colaborador motivado y proactivo, orgulloso de sus logros con IA y con ganas de crecer. Sin embargo, enfrenta desafíos significativos con la gestión de requerimientos de su líder Chelo, lo que le genera frustración y horas extra. Además, existe una deuda técnica crítica y conocimiento clave concentrado en él, lo que representa un riesgo para la operación.",
    "resumen_ia": "Federico es un colaborador motivado y proactivo, orgulloso de sus logros con IA y con ganas de crecer. Sin embargo, enfrenta desafíos significativos con la gestión de requerimientos de su líder Chelo, lo que le genera frustración y horas extra. Además, existe una deuda técnica crítica y conocimiento clave concentrado en él, lo que representa un riesgo para la operación.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "desconexión o conflicto explícito",
    "relacion_lider": "desconexión o conflicto explícito",
    "rel_con_lider": "desconexión o conflicto explícito",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Garcia, Francisco",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "GARCIA, Francisco",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1eC7xUfFrS5CLDGScNMxT91N0hjLJZKa_6N_YuZFZ0qs/edit?usp=drivesdk",
    "fecha_trimestral": "15/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Francisco destaca su orgullo por la coordinación inter-áreas y la mejora en la visibilidad de datos como su principal reto. Muestra un fuerte compromiso con la empresa y el uso de IA, aunque señala una menor frecuencia en las 1:1 con su líder. Su motivación se centra en proyectos de datos y algoritmos, a pesar de interrupciones personales.",
    "resumen_ia": "Francisco destaca su orgullo por la coordinación inter-áreas y la mejora en la visibilidad de datos como su principal reto. Muestra un fuerte compromiso con la empresa y el uso de IA, aunque señala una menor frecuencia en las 1:1 con su líder. Su motivación se centra en proyectos de datos y algoritmos, a pesar de interrupciones personales.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "pide más feedback",
    "relacion_lider": "pide más feedback",
    "rel_con_lider": "pide más feedback",
    "carga": "equilibrio",
    "carga_de_trabajo": "equilibrio",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Gonzalez Cardona, Juan C.",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "GONZALEZ, Juan Carlos",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1BmnghRtPAvDhlrwH9FmjEe0WDvZjvibtDFzS9HnXYKU/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Juan C. Gonzalez Cardona muestra un alto compromiso con la IA, liderando proyectos innovadores y valorando la autonomía del equipo. Se siente motivado y satisfecho con su rol y líder, aunque identifica oportunidades de mejora en procesos internos y desarrollo de autonomía en un compañero. Se ve a sí mismo en la empresa a fin de año.",
    "resumen_ia": "Juan C. Gonzalez Cardona muestra un alto compromiso con la IA, liderando proyectos innovadores y valorando la autonomía del equipo. Se siente motivado y satisfecho con su rol y líder, aunque identifica oportunidades de mejora en procesos internos y desarrollo de autonomía en un compañero. Se ve a sí mismo en la empresa a fin de año.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "equilibrio",
    "carga_de_trabajo": "equilibrio",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Gómez, Matías",
    "area": "Desarrollo",
    "lider_email": "juan@picallex.com",
    "archivo_en_drive": "GOMEZ, Matias",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1h1sE6DtUO06ohYmU1X85WXXDWmpcN7E22UGdGrMvNPA/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Matías está motivado por proyectos de exploración y desarrollo de nuevos productos, aunque se percibe como un cuello de botella en telefonía. Reconoce áreas de mejora personal y se muestra comprometido con la empresa, rechazando ofertas externas. Su principal necesidad es avanzar los proyectos que tiene en mente.",
    "resumen_ia": "Matías está motivado por proyectos de exploración y desarrollo de nuevos productos, aunque se percibe como un cuello de botella en telefonía. Reconoce áreas de mejora personal y se muestra comprometido con la empresa, rechazando ofertas externas. Su principal necesidad es avanzar los proyectos que tiene en mente.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "roces nombrados",
    "vinculo_equipo": "roces nombrados",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Irastorza, Tobías",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "IRASTORZA, Tobias",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1fi7JLvB5p6xcCf9tUOI0fHrL_yn6k1y16pZKAol8iy4/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Lorio, Franco",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "LORIO, Franco",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1EJIja4UgJkuWwJ6IPpWom5g35kBOQpYRxOiwel-q2LY/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Franco es un Tech Lead motivado por proyectos desafiantes y la evolución de la IA, destacando Rocky y la autonomía del equipo. Aunque experimenta una carga de trabajo intensa, valora su relación con el líder y la dirección de la empresa. Se ve a sí mismo en la empresa a fin de año.",
    "resumen_ia": "Franco es un Tech Lead motivado por proyectos desafiantes y la evolución de la IA, destacando Rocky y la autonomía del equipo. Aunque experimenta una carga de trabajo intensa, valora su relación con el líder y la dirección de la empresa. Se ve a sí mismo en la empresa a fin de año.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "esfuerzo excesivo",
    "carga_de_trabajo": "esfuerzo excesivo",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Alerta"
  },
  {
    "nombre_dashboard": "Morales, Damián",
    "area": "Desarrollo",
    "lider_email": "juan@picallex.com",
    "archivo_en_drive": "MORALES, Damian",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1aqtRIWOFNhza9_RYAwQCxb6TROOp8NfOLVVehvkjFCg/edit?usp=drivesdk",
    "fecha_trimestral": "18/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Salzotto, Lucas",
    "area": "Desarrollo",
    "lider_email": "german@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Serra, Agustín",
    "area": "Desarrollo",
    "lider_email": "juan@picallex.com",
    "archivo_en_drive": "SERRA, Agustín",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/11TwE368GwAhXXbWQKpV4aH9jqFSV62OcN7a4QjwzUMA/edit?usp=drivesdk",
    "fecha_trimestral": "8/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Alaminos, Bruno",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Antuna, Juan",
    "area": "Desarrollo",
    "lider_email": "german@picallex.com",
    "archivo_en_drive": "Antuña, Juan",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/16VVjhi9ol8NnbR4_JO0Run0agXx4NEpXNurakZo_Fr4/edit?usp=drivesdk",
    "fecha_trimestral": "22/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "Juan destaca su orgullo por la integración de IA y automatizaciones, especialmente en la creación de compañías. Muestra interés en ciberseguridad y el CRM, manteniendo una buena relación con su equipo y líder. Se siente motivado y estable en la empresa, logrando un buen balance entre trabajo y estudios.",
    "resumen_ia": "Juan destaca su orgullo por la integración de IA y automatizaciones, especialmente en la creación de compañías. Muestra interés en ciberseguridad y el CRM, manteniendo una buena relación con su equipo y líder. Se siente motivado y estable en la empresa, logrando un buen balance entre trabajo y estudios.",
    "riesgo_de_fuga": "Bajo",
    "vinculo": "sin fricciones",
    "vinculo_equipo": "sin fricciones",
    "relacionlider": "fluida",
    "relacion_lider": "fluida",
    "rel_con_lider": "fluida",
    "carga": "equilibrio",
    "carga_de_trabajo": "equilibrio",
    "motivacion": "metas activas y entusiasmo",
    "alerta_salarial": "No",
    "alerta_general": "Ok"
  },
  {
    "nombre_dashboard": "Cardozo, Valentín",
    "area": "Desarrollo",
    "lider_email": "camila@picallex.com",
    "archivo_en_drive": "",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "",
    "fecha_trimestral": "",
    "leida_trimestral": false,
    "ultima_sincronizacion": "",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Yobstraibizer, Facundo",
    "area": "Desarrollo",
    "lider_email": "diego@picallex.com",
    "archivo_en_drive": "YOBSTRAIBIZER, Facundo",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1DjnYRpymMUyeW1FDxVL3ttf5Iqe0-CDLiBRSLH_bPsI/edit?usp=drivesdk",
    "fecha_trimestral": "13/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Franco, Ricardo",
    "area": "Ventas-MKT",
    "lider_email": "carlos@picallex.com",
    "archivo_en_drive": "FRANCO, Ricardo",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1Imfhnc-iv4npqR9CO6VDnWQXX_Df-ZvwH19y-3RmU7E/edit?usp=drivesdk",
    "fecha_trimestral": "18/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  },
  {
    "nombre_dashboard": "Rea, Alimar",
    "area": "Ventas-MKT",
    "lider_email": "carlos@picallex.com",
    "archivo_en_drive": "REA, Alimar",
    "link_mensual": "",
    "fecha_mensual": "",
    "leida_mensual": false,
    "link_trimestral": "https://docs.google.com/document/d/1vqkF73bE-mmsYx48LTYvhBAli22GYXZy8ERrPdxsQvg/edit?usp=drivesdk",
    "fecha_trimestral": "19/5/2026",
    "leida_trimestral": false,
    "ultima_sincronizacion": "1/6/2026",
    "resumen": "",
    "resumen_ia": "",
    "riesgo_de_fuga": "",
    "vinculo": "",
    "vinculo_equipo": "",
    "relacionlider": "",
    "relacion_lider": "",
    "rel_con_lider": "",
    "carga": "",
    "carga_de_trabajo": "",
    "motivacion": "",
    "alerta_salarial": "",
    "alerta_general": ""
  }
]
